docs: Add Azure DevOps Server & Services to integrations readme
SmartBear/swaggerhub-cli pull request #143
Opened 2020-10-01 15:02 UTC by barryadk

* Adding Azure DevOps Server section to README
* Adding Azure DevOps Services section to README
* Adding basic example json configs for each
* Slight reordering of settings in the docs all integrations

2020-10-01 17:40 UTC, hkosova commented on examples/integrations/README.md
> +* **configType**: "AZURE_DEVOPS_SERVER" is used to create a Azure DevOps Server integration.
a Azure -> an Azure?

2020-10-01 17:40 UTC, hkosova commented on examples/integrations/README.md
> +* **configType**: "AZURE_DEVOPS_SERVICES" is used to create a Azure DevOps Service integration.
a Azure -> an Azure?

2020-10-01 17:43 UTC, hkosova commented on examples/integrations/README.md
> +* **projectCollection**: Project collection which contains the target repositories project.
"repositories project" looks like a typo.

2020-10-01 19:39 UTC, hkosova requested changes

2020-10-01 19:39 UTC, hkosova commented on examples/integrations/azure_devops_server.json
> +    "url": "https://azure-devops.onprem.swaggerhub.com",
Consider using an `example.com` domain instead. Also, I think default installations have `/tfs` in their base path / API root.
```suggestion
    "url": "https://azure-devops.example.com/tfs",
```

2020-10-02 08:28 UTC, barryadk commented
Thanks for your feedback @hkosova

2020-10-02 10:30 UTC, conor-ward approved these changes
Looks good, only thinking on this now. Should we add something about Azure DevOps Server only being available to On Premise. Should probably be mentioned on the API itself too.

2020-10-02 11:28 UTC, merged