docs: Update integration properties to table format
SmartBear/swaggerhub-cli pull request #178
Opened 2021-02-08 09:19 UTC by conor-ward

2021-02-08 10:43 UTC, barryadk submitted a review, later dismissed
The table is great improvement to the readability  👍

2021-02-08 10:44 UTC, barryadk commented on examples/integrations/README.md
> +* Amazon API Gateway Integration is not supported in Swggerhub On-Premise
"not _yet_ supported"

2021-02-08 11:38 UTC, barryadk submitted a review, later dismissed

2021-02-08 17:57 UTC, hkosova approved these changes

2021-02-09 19:06 UTC, hkosova requested changes

2021-02-09 19:06 UTC, hkosova commented on examples/integrations/README.md
> +* Amazon API Gateway Integration is not supported yet in Swggerhub On-Premise.
```suggestion
**Notes:** 
* SwaggerHub On-Premise users need v. 1.26 to use the `integration:create` command.
* Amazon API Gateway Integration is not supported yet in SwaggerHub On-Premise.
```

2021-02-10 08:46 UTC, hkosova approved these changes

2021-02-10 09:49 UTC, barryadk approved these changes

2021-02-10 09:54 UTC, merged