feat: Added functionality to update a project
SmartBear/swaggerhub-cli pull request #231
Opened 2021-12-30 11:27 UTC by CalemRoelofsSB

Added functionality to update a project

## Proposed Changes
  - added command `swaggerhub project update owner/project_name` with optional flags:
    - `--description` (Description of project)
    - `-a` or `--apis` (Comma separated list of api names to include in project)
    - `-d` or `--domains` (Comma separated list of domain names to include in project)
  - Added not in command description to inform user that using this command will overwrite whatever is currently saved, and that if they don't include all APIs/domains in the command with the appropriate flags they will be removed

2022-01-04 09:45 UTC, ben-smartbear requested changes

2022-01-04 09:45 UTC, ben-smartbear commented on src/commands/project/update.js
> +            'owner': owner,
as per other pr, https://alligator.io/js/object-property-shorthand-es6/

2022-01-04 09:45 UTC, ben-smartbear commented on src/commands/project/update.js
> +            body: body
https://alligator.io/js/object-property-shorthand-es6/

2022-01-04 09:56 UTC, CalemRoelofsSB commented on src/commands/project/update.js
> +            body: body
Changed now

2022-01-05 11:50 UTC, ben-smartbear approved these changes

2022-01-05 11:54 UTC, merged